// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Middleware defines HTTP middleware that can be applied to the AssetServer.
 * The handler passed as next is the next handler in the chain. One can decide to call the next handler
 * or implement a specialized handling.
 */
export type Middleware = any;
